(source gnu)
(source melpa)

(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "expand-region")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "popwin")
(depends-on "projectile")
(depends-on "s")
(depends-on "smex")
(depends-on "wrap-region")
(depends-on "yasnippet")
(depends-on "pallet")

(depends-on "flycheck")
(depends-on "jedi")
(depends-on "markdown-mode")
(depends-on "twittering-mode")
(depends-on "go-mode")
(depends-on "linum")
(depends-on "auto-complete")
(depends-on "powerline")
